# Generated by Django 5.1.2 on 2024-10-19 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breastcancerApp', '0002_walkchallenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkchallenge',
            old_name='steps_count',
            new_name='steps',
        ),
        migrations.RemoveField(
            model_name='walkchallenge',
            name='participant_name',
        ),
        migrations.RemoveField(
            model_name='walkchallenge',
            name='total_amount_collected',
        ),
        migrations.AddField(
            model_name='walkchallenge',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walkchallenge',
            name='donation',
            field=models.FloatField(default=0),
        ),
    ]
